version: "3.7"

services:
  app:
    image: mahkdev/express-server:v1
    environment:
      - NODE_ENV=production
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file: .env

volumes:
  data:
